# application-dev.properties

spring.datasource.url=jdbc:mysql://localhost:3306/lwd_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Chetan@}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.mail.username=${MAIL_USERNAME:chetanpurkarcp@gmail.com}
spring.mail.password=${MAIL_PASSWORD:zloj cmfg ezmh xztm}

#
#spring.mail.username=chetanpurkarcp@gmail.com
#spring.mail.password=zloj cmfg ezmh xztm