# application-dev.properties

spring.datasource.url=jdbc:mysql://localhost:3306/lwd_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Chetan@}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.mail.username=${MAIL_USERNAME:chetanpurkarcp@gmail.com}
spring.mail.password=${MAIL_PASSWORD:zloj cmfg ezmh xztm}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dwgwofydr}
cloudinary.api-key=${CLOUDINARY_API_KEY:497686488149948}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:pblwW38SITDxQUo7xFig-CiaO_g}
# Multipart limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
